### ISSUE TITLE
Include movie descriptions in list of recommended movies

### ISSUE THREAD

**Issue by irisvukovic** [ADS2024-B2/AgileProject#14]
Each movie from the user's list of recommended movies has a description of the movie pulled from its associated IMDB page.

**Comment by Chlogrct** [comment]
US : As a user, I want to view detailed information about the recommended movies, so that I can decide which ones to watch.
AC : When the user clicks on the recommended movie, they are shown a link that will take them to the IMDB page of the movie.

**Comment by Chlogrct** [comment]
#25
